---
title: "Data_Tidying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(tidyverse)
library(zoo)
library(emphatic)

url <- "https://www.espn.com/soccer/table/_/league/usa.1"

## convert the html code into something R can read
h <- read_html(url)

## grabs the tables
tab <- h %>% html_nodes("table")

test1 <- tab[[1]] %>% html_table()
test2 <- tab[[2]] %>% html_table()

statsfull <- bind_cols(test1, test2)

#test1 <- test1 %>% slice(-1, -15)

statsfull <- statsfull %>% rename("club" = X1...1, "GP" = X1...2, 
                                      "Wins" = X2 , "Draws" = X3 ,
                                      "Losses" = X4 , "Goals For" = X5,
                                      "Goals Against" = X6, "Goal Differential" = X7,
                                      "Points" =  X8)

statsfull <- statsfull %>% slice(-1, -16)

statsfull <- statsfull %>% arrange(desc(Points))

statsfull <- statsfull %>% 
  mutate(Seed = parse_number(club)) %>%
  mutate(newclub = str_remove(club, pattern = "[[:digit:]]+"))

statsfull <- statsfull %>% 
  mutate(newclub2 = fct_recode(newclub, 
                               `New England Revolution` = "NENew England Revolution",
                               `Seattle Sounders FC` = "SEASeattle Sounders FC",
                               `Sporting Kansas City` = "SKCSporting Kansas City",
                               `Colorado Rapids` = "COLColorado Rapids",
                               `Philadelphia Union` = "PHIPhiladelphia Union",
                               `Nashville SC` = "NSHNashville SC",
                               `New York City FC` = "NYCNew York City FC",
                               `Portland Timbers` = "PORPortland Timbers",
                               `Orlando City SC` = "ORLOrlando City SC",
                               `Minnesota United FC` = "MINMinnesota United FC",
                               `Atlanta United FC` = "ATLAtlanta United FC",
                               `LA Galaxy` = "LALA Galaxy",
                               `Vancouver Whitecaps` = "VANVancouver Whitecaps",
                               `New York Red Bulls` = "NYNew York Red Bulls",
                               `Real Salt Lake` = "RSLReal Salt Lake",
                               `D.C. United` = "DCD.C. United",
                               `Columbus Crew` = "CLBColumbus Crew",
                               `LAFC` = "LAFCLAFC",
                               `CF Montréal` = "MTLCF Montréal",
                               `San Jose Earthquakes` = "SJSan Jose Earthquakes",
                               `Inter Miami CF` = "MIAInter Miami CF",
                               `Chicago Fire FC` = "CHIChicago Fire FC",
                               `FC Dallas` = "DALFC Dallas",
                               `Houston Dynamo FC` = "HOUHouston Dynamo FC",
                               `Toronto FC` = "TORToronto FC",
                               `Austin FC` = "ATXAustin FC",
                               `FC Cincinnati` = "CINFC Cincinnati",
                               `Charlotte FC` = "CLTCharlotte FC"))

statsfull <- statsfull %>% select(-club, -newclub)

statsfull <- statsfull %>% select(Seed, newclub2, Points, GP, everything())

statsfull$Points

statsfull <- statsfull %>% mutate(Points = as.integer(Points),
                                  `Goal Differential` = as.integer(`Goal Differential`),
                                  GP = as.integer(GP),
                                  Wins = as.integer(Wins),
                                  Draws = as.integer(Draws),
                                  Losses = as.integer(Losses),
                                  `Goals For` = as.integer(`Goals For`),
                                  `Goals Against` = as.integer(`Goals Against`),
                                  Seed = as.integer(Seed)) 

statsfull <- statsfull %>% arrange(desc(Points)) %>%
  mutate(newclub2 = fct_reorder(newclub2, Points),
         PPG = Points / GP) 

statsfull <- statsfull %>% mutate(Conference = 0)

statsfull <- statsfull %>% mutate(Conference = 
                 case_when(newclub2 == "Philadelphia Union" ~ 0,
                           newclub2 == "LAFC" ~ 1,
                           newclub2 == "Real Salt Lake" ~ 1,
                           newclub2 == "New York Red Bulls" ~ 0,
                           newclub2 == "Atlanta United FC" ~ 0,
                           newclub2 == "Chicago Fire FC" ~ 0,
                           newclub2 == "LA Galaxy" ~ 1,
                           newclub2 == "Columbus Crew" ~ 0,
                           newclub2 == "Orlando City SC" ~ 0,
                           newclub2 == "Austin FC" ~ 1,
                           newclub2 == "FC Dallas" ~ 1,
                           newclub2 == "Colorado Rapids" ~ 1,
                           newclub2 == "Houston Dynamo FC" ~ 1,
                           newclub2 == "Minnesota United FC" ~ 1,
                           newclub2 == "Toronto FC" ~ 0,
                           newclub2 == "Seattle Sounders FC" ~ 1,
                           newclub2 == "Nashville SC" ~ 1,
                           newclub2 == "D.C. United" ~ 0,
                           newclub2 == "Charlotte FC" ~ 0,
                           newclub2 == "FC Cincinnati" ~ 0,
                           newclub2 == "Sporting Kansas City" ~ 1,
                           newclub2 == "Portland Timbers" ~ 1,
                           newclub2 == "New York City FC" ~ 0,
                           newclub2 == "New England Revolution" ~ 0,
                           newclub2 == "CF Montréal" ~ 0,
                           newclub2 == "Vancouver Whitecaps" ~ 1,
                           newclub2 == "San Jose Earthquakes" ~ 1,
                           newclub2 == "Inter Miami CF" ~ 0))
  
statsfull <- statsfull %>% mutate(Conference = if_else(Conference == 0,
                                            true = "East",
                                            false = "West"))

ggplot(data = statsfull, aes(x = newclub2, y = Points)) +
  geom_point() +
  coord_flip()

ggplot(data = statsfull, aes(x = newclub2, y = `Goal Differential`)) +
  geom_point() +
  coord_flip()

ggplot(data = statsfull, aes(x = Conference, y = Points)) +
  geom_boxplot()

ggplot(data = statsfull, aes(x = `Goals For`, y = Points, colour = Conference)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

ggplot(data = statsfull, aes(x = PPG, y = Seed, colour = Conference)) +
  geom_point()
```

```{r}
library(rvest)
library(tidyverse)
library(zoo)

url2 <- "https://www.espn.com/soccer/stats/_/league/usa.1"

## convert the html code into something R can read
h2 <- read_html(url2)

## grabs the tables
gatab <- h2 %>% html_nodes("table")

goal_leaders <- gatab[[1]] %>% html_table()
assist_leaders <- gatab[[2]] %>% html_table()

goal_leaders <- goal_leaders %>%
  rename("Rank" = RK,
         "Player" = Name,
         "Club" = Team,
         "GP" = P,
         "Goals" = G)

assist_leaders <- assist_leaders %>%
  rename("Rank" = RK,
         "Player" = Name,
         "Club" = Team,
         "GP" = P,
         "Assists" = A)

tibble(Rank = c(1, NA, NA, NA, 5, NA, NA, NA))

assist_leaders <- assist_leaders %>% mutate(newrank = na.locf(Rank))

goal_leaders <- goal_leaders %>% mutate(newrank = na.locf(Rank))
```

```{r}
library(rvest)
library(tidyverse)

url3 <- "https://www.transfermarkt.us/major-league-soccer/marktwerteverein/wettbewerb/MLS1/plus/?stichtag=2021-03-15"

## convert the html code into something R can read
h3 <- read_html(url3)

## grabs the tables
valuetab <- h3 %>% html_nodes("table")

#valuetest <- valuetab[[1]] %>% html_table()
#valuetest2 <- valuetab[[2]] %>% html_table()
#valuetest3 <- valuetab[[3]] %>% html_table()
value_df <- valuetab[[4]] %>% html_table()

value_df <- value_df %>% select(1, 3, 5, 6, 7) %>%
  slice(-1)

value_df <- value_df %>% rename("Value_2021" = League,
                                "Value_2022" = `Value Mar 15, 2021`,
                                "Difference" = `Current value`)

value_df <- value_df %>% rename("value22" = Value_2022)

value_df <- value_df %>% mutate(Value_2021 = parse_number(`Value_2021`),
                                Value_2022 = parse_number(`Value_2022`),
                                Difference = parse_number(Difference))

value_df <- value_df %>% mutate(Value_2021 = if_else(Value_2021 > 100,
                                         true = Value_2021 / 1000,
                                         false = Value_2021))

value_df <- value_df %>% mutate(diffind = if_else(Difference < 0,
                                      true = "Decrease",
                                      false = "Increase"))

value_df <- value_df %>% mutate(club = fct_recode(club, 
                                                  LAFC = "Los Angeles FC",
                                                  `LA Galaxy` = "Los Angeles Galaxy",
                                                  `Vancouver Whitecaps` = "Vancouver Whitecaps FC",
                                                  `Real Salt Lake` = "Real Salt Lake City"))

ggplot(data = value_df, aes(x = value22, y = statsfull$Points, colour = diffind)) +
  geom_point() +
  coord_flip()
```

```{r}
library(rvest)
library(tidyverse)

library(readr)
xgoals_df <- read_csv("~/Downloads/american_soccer_analysis_mls_xgoals_teams_2022-04-04.csv")
xgoals_df <- xgoals_df %>% select(-1, -3)

xgoals_df <- xgoals_df %>% rename("club" = Team)

xgoals_df <- xgoals_df %>% mutate(club = fct_recode(club,
                                                    `Philadelphia Union` = "PHI",
                                                    `Real Salt Lake` = "RSL",
                                                    `New York Red Bulls` = "NYRB",
                                                    `Atlanta United FC` = "ATL",
                                                    `Chicago Fire FC` = "CHI",
                                                    `LA Galaxy` = "LAG",
                                                    `Columbus Crew` = "CLB",
                                                    `Orlando City SC` = "ORL",
                                                    `Austin FC` = "ATX",
                                                    `FC Dallas` = "FCD",
                                                    `Colorado Rapids` = "COL",
                                                    `Houston Dynamo FC` = "HOU",
                                                    `Minnesota United FC` = "MIN",
                                                    `Toronto FC` = "TOR",
                                                    `Seattle Sounders FC` = "SEA",
                                                    `Nashville SC` = "NSH",
                                                    `D.C. United` = "DCU",
                                                    `Charlotte FC` = "CLT",
                                                    `FC Cincinnati` = "CIN",
                                                    `Sporting Kansas City` = "SKC",
                                                    `Portland Timbers` = "POR",
                                                    `New York City FC` = "NYC",
                                                    `New England Revolution` = "NER",
                                                    `CF Montréal` = "MTL",
                                                    `Vancouver Whitecaps` = "VAN",
                                                    `San Jose Earthquakes` = "SJE",
                                                    `Inter Miami CF` = "MIA"))
xgoals_df <- xgoals_df %>% mutate(club = fct_reorder(club, Pts))

ggplot(data = xgoals_df, aes(x = club, y = Pts)) +
  geom_point() + 
  geom_segment(aes(x = club, xend = club, y = 0, yend = Pts)) +
  geom_point(aes(x = club, y = xPts, colour = "red")) +
  coord_flip()

ggplot(data = xgoals_df, aes(x = club, y = GF)) +
  geom_point() + 
  geom_segment(aes(x = club, xend = club, y = 0, yend = GF)) +
  geom_point(aes(x = club, y = xGF, colour = "red")) +
  coord_flip()
```

## Joining Data Sets
```{r}
statsfull <- inner_join(statsfull, value_df, by = c("newclub2" = "club"))
statsfull <- inner_join(statsfull, xgoals_df, by = c("newclub2" = "club"))
```

